name: Database Updater
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Update-Readme:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Paste Action
        uses: ShreyamMaity/Copy-Paste-Action@V2.0
        with:
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY : 'student-offers'
          COPY-FILE-LOCATION : './Database/database.md'
          PASTE-FILE-LOCATION : './README.md'
        # pass user input as arguments
